
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AREAS GENERO ID ID_AREAS ID_GENERO ID_LINGUA ID_LINGUAS ID_NOME ID_NOTAS ID_SIN NEWLINE NOME NUMBER TAB TEXTODic : EntradasEntradas : Es EntradasEntradas : EsEs : Id Nome Genero Areas Sin Linguas NotasEs : Id : ID NUMBER NEWLINENome : ID_NOME ':' NOME NEWLINEGenero : ID_GENERO ':' GENERO NEWLINEAreas : ID_AREAS ':' AREAS NEWLINESin : ID_SIN ':' TEXTO NEWLINESin : Linguas : ID_LINGUAS ':' NEWLINE LinguaLingua : TAB ID_LINGUA NOME NEWLINE LinguaLingua : Notas : ID_NOTAS ':' TEXTO NEWLINENotas : "
    
_lr_action_items = {'ID':([0,3,23,28,34,37,39,42,43,],[5,5,-16,-4,-14,-12,-15,-14,-13,]),'$end':([0,1,2,3,6,23,28,34,37,39,42,43,],[-5,0,-1,-3,-2,-16,-4,-14,-12,-15,-14,-13,]),'ID_NOME':([4,13,],[8,-6,]),'NUMBER':([5,],[9,]),'ID_GENERO':([7,22,],[11,-7,]),':':([8,11,15,19,24,29,],[12,16,20,25,30,33,]),'NEWLINE':([9,17,21,26,30,31,36,41,],[13,22,27,32,34,35,39,42,]),'ID_AREAS':([10,27,],[15,-8,]),'NOME':([12,40,],[17,41,]),'ID_SIN':([14,32,],[19,-9,]),'ID_LINGUAS':([14,18,32,35,],[-11,24,-9,-10,]),'GENERO':([16,],[21,]),'AREAS':([20,],[26,]),'ID_NOTAS':([23,34,37,42,43,],[29,-14,-12,-14,-13,]),'TEXTO':([25,33,],[31,36,]),'TAB':([34,42,],[38,38,]),'ID_LINGUA':([38,],[40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Dic':([0,],[1,]),'Entradas':([0,3,],[2,6,]),'Es':([0,3,],[3,3,]),'Id':([0,3,],[4,4,]),'Nome':([4,],[7,]),'Genero':([7,],[10,]),'Areas':([10,],[14,]),'Sin':([14,],[18,]),'Linguas':([18,],[23,]),'Notas':([23,],[28,]),'Lingua':([34,42,],[37,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Dic","S'",1,None,None,None),
  ('Dic -> Entradas','Dic',1,'p_dic','my_parser.py',7),
  ('Entradas -> Es Entradas','Entradas',2,'p_entradas','my_parser.py',11),
  ('Entradas -> Es','Entradas',1,'p_entradas_ultimo','my_parser.py',15),
  ('Es -> Id Nome Genero Areas Sin Linguas Notas','Es',7,'p_es','my_parser.py',19),
  ('Es -> <empty>','Es',0,'p_es_vazio','my_parser.py',24),
  ('Id -> ID NUMBER NEWLINE','Id',3,'p_Id','my_parser.py',28),
  ('Nome -> ID_NOME : NOME NEWLINE','Nome',4,'p_Nome','my_parser.py',34),
  ('Genero -> ID_GENERO : GENERO NEWLINE','Genero',4,'p_Genero','my_parser.py',40),
  ('Areas -> ID_AREAS : AREAS NEWLINE','Areas',4,'p_Areas','my_parser.py',45),
  ('Sin -> ID_SIN : TEXTO NEWLINE','Sin',4,'p_Sin','my_parser.py',51),
  ('Sin -> <empty>','Sin',0,'p_Sin_vazio','my_parser.py',57),
  ('Linguas -> ID_LINGUAS : NEWLINE Lingua','Linguas',4,'p_Linguas','my_parser.py',62),
  ('Lingua -> TAB ID_LINGUA NOME NEWLINE Lingua','Lingua',5,'p_Lingua','my_parser.py',68),
  ('Lingua -> <empty>','Lingua',0,'p_Lingua_vazio','my_parser.py',73),
  ('Notas -> ID_NOTAS : TEXTO NEWLINE','Notas',4,'p_Notas','my_parser.py',77),
  ('Notas -> <empty>','Notas',0,'p_Notas_vazio','my_parser.py',82),
]
