
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AREAS GENERO ID ID_AREAS ID_GENERO ID_LINGUA ID_LINGUAS ID_NOME ID_NOTAS ID_SIN NEWLINE NOME NUMBER TAB TEXTOEs : Id Nome Genero Areas Sin Linguas NotasId : ID ':' NUMBERNome : ID_NOME ':' NOMEGenero : ID_GENERO ':' GENEROAreas : ID_AREAS ':' AREASSin : ID_SIN ':' TEXTOSin : Linguas : ID_LINGUAS ':' NEWLINE LinguaLingua : TAB ID_LINGUA NOME NEWLINE LinguaLingua : Notas : ID_NOTAS ':' TEXTONotas : "
    
_lr_action_items = {'ID':([0,],[3,]),'$end':([1,19,23,28,29,30,34,35,],[0,-12,-1,-10,-11,-8,-10,-9,]),'ID_NOME':([2,10,],[5,-2,]),':':([3,5,8,12,16,20,24,],[6,9,13,17,21,25,27,]),'ID_GENERO':([4,14,],[8,-3,]),'NUMBER':([6,],[10,]),'ID_AREAS':([7,18,],[12,-4,]),'NOME':([9,32,],[14,33,]),'ID_SIN':([11,22,],[16,-5,]),'ID_LINGUAS':([11,15,22,26,],[-7,20,-5,-6,]),'GENERO':([13,],[18,]),'AREAS':([17,],[22,]),'ID_NOTAS':([19,28,30,34,35,],[24,-10,-8,-10,-9,]),'TEXTO':([21,27,],[26,29,]),'NEWLINE':([25,33,],[28,34,]),'TAB':([28,34,],[31,31,]),'ID_LINGUA':([31,],[32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Es':([0,],[1,]),'Id':([0,],[2,]),'Nome':([2,],[4,]),'Genero':([4,],[7,]),'Areas':([7,],[11,]),'Sin':([11,],[15,]),'Linguas':([15,],[19,]),'Notas':([19,],[23,]),'Lingua':([28,34,],[30,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Es","S'",1,None,None,None),
  ('Es -> Id Nome Genero Areas Sin Linguas Notas','Es',7,'p_es','my_parser.py',7),
  ('Id -> ID : NUMBER','Id',3,'p_Id','my_parser.py',11),
  ('Nome -> ID_NOME : NOME','Nome',3,'p_Nome','my_parser.py',15),
  ('Genero -> ID_GENERO : GENERO','Genero',3,'p_Genero','my_parser.py',19),
  ('Areas -> ID_AREAS : AREAS','Areas',3,'p_Areas','my_parser.py',23),
  ('Sin -> ID_SIN : TEXTO','Sin',3,'p_Sin','my_parser.py',28),
  ('Sin -> <empty>','Sin',0,'p_Sin_vazio','my_parser.py',33),
  ('Linguas -> ID_LINGUAS : NEWLINE Lingua','Linguas',4,'p_Linguas','my_parser.py',38),
  ('Lingua -> TAB ID_LINGUA NOME NEWLINE Lingua','Lingua',5,'p_Lingua','my_parser.py',42),
  ('Lingua -> <empty>','Lingua',0,'p_Lingua_vazio','my_parser.py',45),
  ('Notas -> ID_NOTAS : TEXTO','Notas',3,'p_Notas','my_parser.py',49),
  ('Notas -> <empty>','Notas',0,'p_Notas_vazio','my_parser.py',53),
]
